spring:
  application:
    name: CareBridgeAdminAPI

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.10.10.105:13307/caredb
    username: careuser
    password: careuser


    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.zaxxer: info
    org.springframework: info


  type-aliases-package: org.carebridge.carebridgeadminapi.**.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl