spring:
  application:
    name: CareBridgeAdminAPI

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.10.10.105:13306/caredb
    username: careuser
    password: careuser


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.demo.springdemo2.**.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl