spring:
  application:
    name: CareBridgeAdminAPI

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/caredb
    username: careuser
    password: careuser


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.carebridge.carebridgeadminapi.**
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl