spring:
  application:
    name: CareBridgeAdminAPI

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/caredb
    username: careuser
    password: careuser

